### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ProfessionalMe** [wuditken/MillionHeroes#10]
Traceback (most recent call last):
  File "hero.py", line 1, in <module>
    import urllib.request, sys,base64,json,os,time,pyperclip,baiduSearch
ModuleNotFoundError: No module named 'pyperclip'

错误信息如上

**Comment by wuditken** [comment]
命令行运行pip install 模块 发自网易邮箱大师 在2018年01月11日 08:56，fengyufei 写道： Traceback (most recent call last): File "hero.py", line 1, in import urllib.request, sys,base64,json,os,time,pyperclip,baiduSearch ModuleNotFoundError: No module named 'pyperclip' 错误信息如上 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
