### ISSUE TITLE
使用过程中出现的问题

### ISSUE THREAD

**Issue by zhuanli555** [wuditken/MillionHeroes#17]
1.
![image](https://user-images.githubusercontent.com/11409298/34857379-68489daa-f785-11e7-917a-e5f5087aad64.png)
出现字符不能解析的情况
2.
Traceback (most recent call last): File "hero.py", line 56, in <module> results = baiduSearch.search(keyword) File "D:\MillionHeroes-master\baiduSearch\search.py", line 8, in search results = process.page(page) File "D:\MillionHeroes-master\baiduSearch\process.py", line 46, in page result_set = result_set.find_all('div', class_='c-container') # 结果class固定，其余为硬广 AttributeError: 'NoneType' object has no attribute 'find_all'
出现找不到内容的情况

**Comment by zhuanli555** [comment]
我测了一下，第一个问题是因为\xa9,\xa0等字符属于latin1 （ISO/IEC_8859-1）中的扩展字符集字符，无法解析，可以在代码中改一下去掉不对的字符
![image](https://user-images.githubusercontent.com/11409298/34858247-260e7e8c-f78a-11e7-93b2-14241a8ed2e3.png)

**Comment by zhuanli555** [comment]
第二个问题昨天12题中会出现好几次，我看了之前同学提的问题和解答，意思是图片没有识别成功？这个百度ocr的正确率也太低了😂

**Comment by zhuanli555** [comment]
![image](https://user-images.githubusercontent.com/11409298/34858452-6d7fbbc2-f78b-11e7-9aa5-c3991a37ea9d.png)
😂更加完善一点

**Comment by zhuanli555** [comment]
今晚百万英雄战个痛快😄

**Comment by zhuanli555** [comment]
im = Image.open(r'1.png')
r,g,b,a = im.split()
im = Image.merge('RGB',(r,g,b))
im.save(r'2.jpg')
把png格式的转成jpg格式是坠吼的

**Comment by wuditken** [comment]
请提交pr
